### PR TITLE
Lepton preselection for vertex refit

### PR DESCRIPTION
**Pull request by aknayak**
Added preselection to leptons that are input to the refitted vertices excluding tau tracks, to reduce ntuple processing time and size. Also, there is a code to produce a collection of regular vertices with BeamSpot  constraint. This collection is not saved in MiniAOD events.

### CODE REVIEW

**Comment by thomas-mueller** [comment]
Thanks, Arun!

Wouldn't it make sense to do the changes in the existing files instead of adding new ones?

**Comment by azotz** [comment]
Is it enough to only update the `srcTaus` and `srcLeptons` in the [python/LeptonPreSelections_cfi.py](https://github.com/artus-analysis/TauRefit/pull/1/commits/eeb4e71b6022a341a5258bface4eb439795ec7f1#diff-9380169e0bdc7b02b047ba454bb52377)? What about the `srcElectrons` and `srcMuons`?

**Comment by aknayak** [comment]
Hi Thomas,
I added new file so that if someone does not want to apply any preselection he/she can simply use the old configuration. Do you think it is more suitable for everyone if the existing file is updated? 
Actually, srcElectrons, srcMuons, and srcTaus are not used at all  https://github.com/artus-analysis/TauRefit/blob/master/plugins/AdvancedRefitVertexProducer.cc#L66-L73
Only srcLeptons are used. I should remove srcTaus too.

**Comment by thomas-mueller** [comment]
Yes, sounds good. I will then accept the PR. You should also have commit rights in the repository. So you could remove code that is not needed after the merge, if you have time.

**Pull request merged**
